-- 코드를 입력하세요
# SELECT F.FLAVOR, (F.TOTAL_ORDER+J.TOTAL_ORDER) AS TOTAL
# FROM FIRST_HALF AS F LEFT JOIN JULY AS J
# ON F.SHIPMENT_ID = J.SHIPMENT_ID
# UNION
# SELECT J.FLAVOR, (F.TOTAL_ORDER+J.TOTAL_ORDER) AS TOTAL
# FROM JULY AS J LEFT JOIN FIRST_HALF AS F
# ON F.SHIPMENT_ID = J.SHIPMENT_ID
# WHERE J.FLAVOR IS NULL
# ORDER BY TOTAL DESC
# LIMIT 3

# SELECT F.FLAVOR
# FROM FIRST_HALF AS F JOIN JULY AS J
# GROUP BY FLAVOR
# ORDER BY (F.TOTAL_ORDER+SUM(J.TOTAL_ORDER)) DESC
# LIMIT 3

SELECT F.FLAVOR
FROM FIRST_HALF AS F
JOIN JULY AS J ON F.FLAVOR = J.FLAVOR
GROUP BY F.FLAVOR
ORDER BY F.TOTAL_ORDER + SUM(J.TOTAL_ORDER) DESC
LIMIT 3;
