-- 코드를 입력하세요
SELECT BOOK_ID, AUTHOR_NAME, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK, AUTHOR
WHERE BOOK.CATEGORY = '경제' AND BOOK.AUTHOR_ID = AUTHOR.AUTHOR_ID
ORDER BY PUBLISHED_DATE ASC

#SELECT * FROM BOOK WHERE BOOK.CATEGORY = '경제'
